name: PR
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "smb://test.s1.local/test1" >> $GITHUB_STEP_SUMMARY
          echo '<a href="smb://test.s1.local/test1">test</a>' >> $GITHUB_STEP_SUMMARY
          echo '[test](smb://test.s1.local/test1)' >> $GITHUB_STEP_SUMMARY
